load('/results/1_50_ResultsWithReturnAll.mat')
restable{1}{1}=resTable;
load('/results/2_50_ResultsWithReturnAll.mat')
restable{1}{2}=resTable;
load('/results/3_50_ResultsWithReturnAll.mat')
restable{1}{3}=resTable;
load('/results/4_50_ResultsWithReturnAll.mat')
restable{1}{4}=resTable;
load('/results/5_50_ResultsWithReturnAll.mat')
restable{1}{5}=resTable;
load('/results/1_100_ResultsWithReturnAll.mat')
restable{2}{1}=resTable;
load('/results/2_100_ResultsWithReturnAll.mat')
restable{2}{2}=resTable;
load('/results/3_100_ResultsWithReturnAll.mat')
restable{2}{3}=resTable;
load('/results/4_100_ResultsWithReturnAll.mat')
restable{2}{4}=resTable;
load('/results/5_100_ResultsWithReturnAll.mat')
restable{2}{5}=resTable;
load('/results/1_200_ResultsWithReturnAll.mat')
restable{3}{1}=resTable;
load('/results/2_200_ResultsWithReturnAll.mat')
restable{3}{2}=resTable;
load('/results/3_200_ResultsWithReturnAll.mat')
restable{3}{3}=resTable;
load('/results/4_200_ResultsWithReturnAll.mat')
restable{3}{4}=resTable;
load('/results/5_200_ResultsWithReturnAll.mat')
restable{3}{5}=resTable;
cmacamp=colormap
forplots
plots